1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [1]:
import numpy as np

In [10]:
arr = np.random.randint(1,100,size=(3,3))
arr

array([[44, 42, 69],
       [87, 21, 37],
       [99, 40, 75]])

In [11]:
arr.T

array([[44, 87, 99],
       [42, 21, 40],
       [69, 37, 75]])

2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [21]:
arr = np.random.randint(1,20,size=(10))
arr.ndim

1

In [22]:
arr

array([10,  8, 17, 11, 12,  1, 10,  4, 16,  7])

In [25]:
arr1 = arr.reshape(2,5)
arr1

array([[10,  8, 17, 11, 12],
       [ 1, 10,  4, 16,  7]])

In [26]:
arr1.reshape(5,2)

array([[10,  8],
       [17, 11],
       [12,  1],
       [10,  4],
       [16,  7]])

3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [28]:
arr = np.random.rand(4,4)
arr

array([[0.82381253, 0.06744148, 0.96964934, 0.89826934],
       [0.53338405, 0.01368424, 0.03092219, 0.63593436],
       [0.75396829, 0.4012747 , 0.88330189, 0.40537087],
       [0.01297135, 0.92388428, 0.48396868, 0.14216526]])

In [40]:
array_6x6 = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(array_6x6)

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.82381253 0.06744148 0.96964934 0.89826934 0.        ]
 [0.         0.53338405 0.01368424 0.03092219 0.63593436 0.        ]
 [0.         0.75396829 0.4012747  0.88330189 0.40537087 0.        ]
 [0.         0.01297135 0.92388428 0.48396868 0.14216526 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [44]:
l = list(range(10,61,5))
arr = np.array(l)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

In [50]:
arr = np.array(["python","numpy","pandas"])
arr1 = np.char.upper(arr)
arr1

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [52]:
arr2 = np.char.lower(arr)
arr2

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [53]:
arr3 = np.char.title(arr)
arr3

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

6. Generate a NumPy array of words. Insert a space between each character of every word in the array

In [54]:
words_array = np.array(["python", "numpy", "pandas"])
spaced_words_array = np.char.join(" ", words_array)
spaced_words_array

array(['p y t h o n', 'n u m p y', 'p a n d a s'], dtype='<U11')

7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [55]:
arr1 = np.random.randint(1,10,size=(3,3))
arr2 = np.random.randint(1,10,size=(3,3))


In [59]:
print(arr1,"\n\n",arr2)

[[6 6 6]
 [4 7 3]
 [6 6 1]] 

 [[7 3 5]
 [4 7 5]
 [5 1 1]]


In [56]:
#addition
arr1 + arr2

array([[13,  9, 11],
       [ 8, 14,  8],
       [11,  7,  2]])

In [60]:
#subtraction
arr1 - arr2

array([[-1,  3,  1],
       [ 0,  0, -2],
       [ 1,  5,  0]])

In [61]:
#multiplication
arr1 * arr2

array([[42, 18, 30],
       [16, 49, 15],
       [30,  6,  1]])

In [62]:
#division
arr1 / arr2

array([[0.85714286, 2.        , 1.2       ],
       [1.        , 1.        , 0.6       ],
       [1.2       , 6.        , 1.        ]])

8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [65]:
arr = np.eye(5,5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [66]:
diagonal_elements = np.diag(arr)
diagonal_elements

array([1., 1., 1., 1., 1.])

9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.

In [70]:
l = list(range(1,101))
arr = np.array(l)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [81]:
bool1 = True
for i in range(2, 100):
    bool1 = True  
    for j in range(2, int(i**0.5) + 1): 
        if i % j == 0:
            bool1 = False
            break
    if bool1:
        print(i, "is a prime number")


2 is a prime number
3 is a prime number
5 is a prime number
7 is a prime number
11 is a prime number
13 is a prime number
17 is a prime number
19 is a prime number
23 is a prime number
29 is a prime number
31 is a prime number
37 is a prime number
41 is a prime number
43 is a prime number
47 is a prime number
53 is a prime number
59 is a prime number
61 is a prime number
67 is a prime number
71 is a prime number
73 is a prime number
79 is a prime number
83 is a prime number
89 is a prime number
97 is a prime number


10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

In [92]:
temp = np.random.randint(20,40,size=(28))
temp

array([24, 27, 34, 37, 20, 25, 39, 34, 24, 27, 21, 26, 21, 22, 23, 31, 27,
       38, 21, 22, 29, 31, 20, 35, 20, 28, 30, 36])

In [98]:
week1 = temp[0:7]
print("Avg. temp of week1:",week1.mean())
week1

Avg. temp of week1: 29.428571428571427


array([24, 27, 34, 37, 20, 25, 39])

In [101]:
week2 = temp[7:14]
print("Avg. temp of week2:",week2.mean())
week2

Avg. temp of week2: 25.0


array([34, 24, 27, 21, 26, 21, 22])

In [102]:
week3 = temp[14:21]
print("Avg. temp of week3:",week3.mean())
week3

Avg. temp of week3: 27.285714285714285


array([23, 31, 27, 38, 21, 22, 29])

In [103]:
week4 = temp[21:28]
print("Avg. temp of week4:",week4.mean())
week4

Avg. temp of week4: 28.571428571428573


array([31, 20, 35, 20, 28, 30, 36])